"""Problem 3 package."""

from .solver import (
    KNOWN_OPTIMUM_E_N20,
    KNOWN_OPTIMUM_F_N20,
    QuantumRunResult,
    autocorrelations,
    build_labs_hamiltonian,
    build_labs_term_dictionary,
    classical_simulated_annealing_labs,
    labs_energy,
    merit_factor,
    merit_ratio_from_energy,
    one_flip_local_search,
    optimize_qaoa_labs,
    optimize_vqe_labs,
    pm_string_from_spins,
    quantum_seeded_local_search,
    random_sampling_baseline,
    run_problem3_benchmark,
    spins_from_pm_string,
    verify_barker_n11,
)

__all__ = [
    "KNOWN_OPTIMUM_E_N20",
    "KNOWN_OPTIMUM_F_N20",
    "QuantumRunResult",
    "autocorrelations",
    "build_labs_hamiltonian",
    "build_labs_term_dictionary",
    "classical_simulated_annealing_labs",
    "labs_energy",
    "merit_factor",
    "merit_ratio_from_energy",
    "one_flip_local_search",
    "optimize_qaoa_labs",
    "optimize_vqe_labs",
    "pm_string_from_spins",
    "quantum_seeded_local_search",
    "random_sampling_baseline",
    "run_problem3_benchmark",
    "spins_from_pm_string",
    "verify_barker_n11",
]
